[package]
name = "const_graphs"
version = "0.2.1"
edition = "2021"
license = "LGPL-2.1"
description = "Blazingly-fast compile-time copy-free graph crate"
repository = "https://github.com/TiagoCavalcante/const_graphs"
